=== circlesland/circles-monorepo/packages/frame-app/schemas/root-manifest.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Applications",
  "description": "A list of applications that will be loaded inside the frame",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "label": {
        "type": "string"
      },
      "icon": {
        "type": "string"
      },
      "url": {
        "type": "string"
      },
      "manifest": {
        "type": "string"
      }
    },
    "required": ["id", "label", "icon", "url", "manifest"]
  },
  "minItems": 1,
  "uniqueItems": true
}

=== circlesland/circles-monorepo/packages/frame-app/apps/root.json
[
  {
    "id": "123123",
    "label": "Wallet dApp",
    "icon": "https://circles.land/logos/circles.png",
    "url": "https://example.com",
    "manifest": "https://dummyjson.com/products/1"
  },
  {
    "id": "123126",
    "label": "Marketplace",
    "icon": "https://circles.land/logos/circles.png",
    "url": "https://circles.land",
    "manifest": "https://dummyjson.com/products/1"
  }
]
